title: ""
baseurl: ""
collections_dir: content

collections:
  data_elements:
    output: true
  first_letters:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "data_elements"
    values:
      layout: "data_element"
  -
    scope:
      path: ""
      type: "first_letters"
    values:
      layout: "first_letter"